Add docker file

diff --git a/Tools/build-dependencies b/Tools/build-dependencies
--- a/Tools/build-dependencies
+++ b/Tools/build-dependencies
@@ -10,7 +10,6 @@ fi
 TOOLS_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 PROJECT_ROOT=${PROJECT_ROOT:-$(cd "$TOOLS_ROOT" && cd $(git rev-parse --show-toplevel) && pwd)}
 DEPENDENCIES_ROOT=${DEPENDENCIES_ROOT:-$PROJECT_ROOT/.dependencies}
-PKG_CONFIG_ROOT=${PKG_CONFIG_ROOT:-/usr/local/lib/pkgconfig}
 INSTALL_PATH=${INSTALL_PATH:-$DEPENDENCIES_ROOT/installed}
 LLVM_COMMIT=${LLVM_COMMIT:-$(cat $TOOLS_ROOT/llvm-commit)}
 LLVM_REPO=${LLVM_REPO:-https://github.com/llvm/llvm-project}
@@ -29,7 +28,8 @@ LLVM_HEADER_TARGETS="
   install-mlir-headers
   $LLVM_ADDITIONAL_HEADER_TARGETS"
 TOOLS_INSTALL_PATH="$DEPENDENCIES_ROOT/installed/tools"
-PKG_CONFIG_PATH="$PKG_CONFIG_ROOT/LLVM-for-Swift.pc"
+PKG_CONFIG_PATH=${PKG_CONFIG_PATH:-/usr/local/lib/pkgconfig}
+PKG_CONFIG_FILE_PATH="$PKG_CONFIG_PATH/LLVM-for-Swift.pc"
 PKG_CONFIG=$(cat << EOF
 prefix=$INSTALL_PATH
 
@@ -37,9 +37,9 @@ Name: LLVM for Swift
 Description: LLVM, potentially with additional projects. Installed using Utilities/build-dependencies in MLIRSwift.
 Version: local
 Cflags: -I\${prefix}/include
-Libs: -lc++ -lcurses $(
+Libs: -lcurses $(
   # For some reason, linking the C++ standard libary explicitly is necessary on Linux but breaks the macOS build.
-  [[ "$OSTYPE" == "darwin"* ]] || echo "-lstdc++"
+  [[ "$OSTYPE" == "darwin"* ]] && echo "-lc++" || echo "-lstdc++"
 ) -L\${prefix}/lib
 EOF
 )
@@ -71,7 +71,7 @@ fi
 echo "   - Built products will be placed in ${LLVM_BUILD_ROOT}"
 echo " - Install all available LLVM projects to ${INSTALL_PATH}"
 echo " - Install necessary tools to ${TOOLS_INSTALL_PATH}"
-echo " - Update ${PKG_CONFIG_PATH} to point to ${INSTALL_PATH}"
+echo " - Update ${PKG_CONFIG_FILE_PATH} to point to ${INSTALL_PATH}"
 echo ""
 
 if [[ "$NO_INTERACTION" != "true" ]]; then
@@ -134,10 +134,10 @@ cmake \
   --target $(echo $LLVM_INSTALL_TARGETS)
 
 # Install the LLVM package config
-if [[ -n "$PKG_CONFIG_ROOT" ]]; then
-  echo "Writing pkg-config file to $PKG_CONFIG_PATH"
-  if ! echo "$PKG_CONFIG" > "$PKG_CONFIG_PATH"; then
-    echo "Could not create pkg-config file, please ensure $PKG_CONFIG_PATH is writable."
+if [[ -n "$PKG_CONFIG_FILE_PATH" ]]; then
+  echo "Writing pkg-config file to $PKG_CONFIG_FILE_PATH"
+  if ! echo "$PKG_CONFIG" > "$PKG_CONFIG_FILE_PATH"; then
+    echo "Could not create pkg-config file, please ensure $PKG_CONFIG_FILE_PATH is writable."
     exit 1
   fi
 fi
